import type { CategoryId, UrbanCategory } from "./types";

/**
 * Snapshot date of the official Places API (New) Table A used for this
 * taxonomy: https://developers.google.com/maps/documentation/places/web-service/place-types
 */
export const GOOGLE_TABLE_A_SNAPSHOT = "2026-07-20";

/**
 * Mutually exclusive product categories. All listed values are filterable
 * Table A primary types. Parent types are intentionally used where Google
 * expands their subtype hierarchy (for example, `restaurant`, `museum`,
 * `park`, and `gym`).
 */
export const CATEGORIES = [
  {
    id: "food_drink",
    label: "Alimentação e bebida",
    shortLabel: "Alimentação",
    description:
      "Restaurantes, cafés, bares e opções de alimentação cotidiana.",
    color: "#F97316",
    googlePrimaryTypes: [
      "restaurant",
      "cafe",
      "coffee_shop",
      "bakery",
      "bar",
      "pub",
      "meal_delivery",
      "meal_takeaway",
      "food_court",
      "ice_cream_shop",
      "juice_shop",
      "tea_house",
      "dessert_shop",
      "confectionery",
      "brewery",
      "winery",
    ],
  },
  {
    id: "shopping_supply",
    label: "Compras e abastecimento",
    shortLabel: "Compras",
    description:
      "Mercados, lojas e estabelecimentos para compras e abastecimento.",
    color: "#EAB308",
    googlePrimaryTypes: [
      "supermarket",
      "grocery_store",
      "convenience_store",
      "market",
      "shopping_mall",
      "department_store",
      "discount_store",
      "food_store",
      "book_store",
      "clothing_store",
      "electronics_store",
      "hardware_store",
      "home_goods_store",
      "home_improvement_store",
      "furniture_store",
      "pet_store",
      "bicycle_store",
      "auto_parts_store",
      "sporting_goods_store",
      "warehouse_store",
      "wholesaler",
    ],
  },
  {
    id: "health_wellbeing",
    label: "Saúde e bem-estar",
    shortLabel: "Saúde",
    description:
      "Hospitais, clínicas, profissionais de saúde, farmácias e cuidado pessoal.",
    color: "#EF4444",
    googlePrimaryTypes: [
      "chiropractor",
      "dental_clinic",
      "dentist",
      "doctor",
      "drugstore",
      "general_hospital",
      "hospital",
      "massage",
      "massage_spa",
      "medical_center",
      "medical_clinic",
      "medical_lab",
      "pharmacy",
      "physiotherapist",
      "skin_care_clinic",
      "spa",
      "wellness_center",
    ],
  },
  {
    id: "education_knowledge",
    label: "Educação e conhecimento",
    shortLabel: "Educação",
    description:
      "Escolas, universidades, bibliotecas e instituições de pesquisa.",
    color: "#3B82F6",
    googlePrimaryTypes: [
      "academic_department",
      "educational_institution",
      "library",
      "preschool",
      "primary_school",
      "research_institute",
      "school",
      "secondary_school",
      "university",
    ],
  },
  {
    id: "culture_leisure_nature",
    label: "Cultura, lazer, esporte e natureza",
    shortLabel: "Lazer",
    description:
      "Cultura, entretenimento, parques, natureza e instalações esportivas.",
    color: "#22C55E",
    googlePrimaryTypes: [
      "art_gallery",
      "art_museum",
      "cultural_center",
      "historical_place",
      "history_museum",
      "museum",
      "performing_arts_theater",
      "tourist_attraction",
      "movie_theater",
      "event_venue",
      "botanical_garden",
      "garden",
      "city_park",
      "dog_park",
      "national_park",
      "park",
      "plaza",
      "state_park",
      "wildlife_refuge",
      "nature_preserve",
      "beach",
      "fitness_center",
      "gym",
      "playground",
      "sports_complex",
      "stadium",
      "swimming_pool",
      "yoga_studio",
    ],
  },
  {
    id: "mobility_automotive",
    label: "Mobilidade e automóvel",
    shortLabel: "Mobilidade",
    description:
      "Transporte coletivo, mobilidade compartilhada e infraestrutura automotiva.",
    color: "#06B6D4",
    googlePrimaryTypes: [
      "airport",
      "bike_sharing_station",
      "bus_station",
      "bus_stop",
      "ferry_terminal",
      "light_rail_station",
      "subway_station",
      "taxi_service",
      "taxi_stand",
      "train_station",
      "tram_stop",
      "transit_depot",
      "transit_station",
      "transit_stop",
      "transportation_service",
      "parking",
      "parking_garage",
      "parking_lot",
      "gas_station",
      "electric_vehicle_charging_station",
      "ebike_charging_station",
      "car_dealer",
      "car_rental",
      "car_repair",
      "car_wash",
    ],
  },
  {
    id: "services_finance_work",
    label: "Serviços, finanças e trabalho",
    shortLabel: "Serviços",
    description:
      "Serviços pessoais e profissionais, finanças e espaços de trabalho flexível.",
    color: "#8B5CF6",
    googlePrimaryTypes: [
      "accounting",
      "atm",
      "bank",
      "business_center",
      "coworking_space",
      "barber_shop",
      "beauty_salon",
      "consultant",
      "courier_service",
      "electrician",
      "employment_agency",
      "florist",
      "insurance_agency",
      "laundry",
      "lawyer",
      "locksmith",
      "moving_company",
      "nail_salon",
      "plumber",
      "real_estate_agency",
      "storage",
      "tailor",
      "telecommunications_service_provider",
      "tour_agency",
      "travel_agency",
      "veterinary_care",
    ],
  },
  {
    id: "civic_community",
    label: "Cívico e comunitário",
    shortLabel: "Cívico",
    description:
      "Governo, segurança, equipamentos comunitários e locais de culto.",
    color: "#64748B",
    googlePrimaryTypes: [
      "city_hall",
      "courthouse",
      "embassy",
      "fire_station",
      "government_office",
      "local_government_office",
      "police",
      "post_office",
      "public_bath",
      "public_bathroom",
      "community_center",
      "association_or_organization",
      "non_profit_organization",
      "cemetery",
      "buddhist_temple",
      "church",
      "hindu_temple",
      "mosque",
      "shinto_shrine",
      "synagogue",
    ],
  },
] as const satisfies readonly UrbanCategory[];

export const CATEGORY_BY_ID: Readonly<
  Record<CategoryId, UrbanCategory>
> = {
  food_drink: CATEGORIES[0],
  shopping_supply: CATEGORIES[1],
  health_wellbeing: CATEGORIES[2],
  education_knowledge: CATEGORIES[3],
  culture_leisure_nature: CATEGORIES[4],
  mobility_automotive: CATEGORIES[5],
  services_finance_work: CATEGORIES[6],
  civic_community: CATEGORIES[7],
};

export const ALL_GOOGLE_PRIMARY_TYPES = CATEGORIES.flatMap(
  (category) => category.googlePrimaryTypes,
);

export function getCategory(categoryId: CategoryId): UrbanCategory {
  return CATEGORY_BY_ID[categoryId];
}
